name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package -DskipTests --file Backend/demo/pom.xml

  docker-and-deploy:
    needs: build-and-test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and remove old container (compose)
        run: docker compose down || true
        working-directory: Backend/demo

      - name: Free port 8081 if in use
        run: fuser -k 8081/tcp || true
        working-directory: Backend/demo

      - name: Deploy with Docker Compose
        run: docker compose up -d --build
        working-directory: Backend/demo

      - name: List running containers
        run: docker ps