name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  git-pull:
    runs-on: self-hosted
    steps:
      - name: Git pull latest code
        run: |
          cd ${{ github.workspace }}
          git pull origin main

  build-and-test:
    needs: git-pull
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests --file Backend/demo/pom.xml

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: demo-jar
          path: Backend/demo/target/demo-0.0.1-SNAPSHOT.jar

  docker-and-deploy:
    needs: build-and-test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: demo-jar
          path: Backend/demo/target

      - name: Build Docker image with Compose
        run: |
          cd Backend/demo
          docker compose build

      - name: Stop and remove old container (Compose Down)
        run: |
          cd Backend/demo
          docker compose down || true

      - name: Remove old examspace container if exists
        run: |
          docker rm -f examspace || true

      - name: Free port 8081 if in use
        run: |
          fuser -k 8081/tcp || true

      - name: Start container with Compose Up
        run: |
          cd Backend/demo
          docker compose up -d

      - name: List running containers
        run: docker ps